name: Build TOQUE Server Banner

on:
  push:
    paths:
      - "client-server-banner/**"
      - ".github/workflows/build-toque-server-banner.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client-server-banner

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10.2"

      - name: Build
        run: gradle build --no-daemon

      - name: Upload client mod
        uses: actions/upload-artifact@v4
        with:
          name: toque-server-banner
          path: client-server-banner/build/libs/toque-server-banner-*.jar
